# Generated by Django 5.2.6 on 2025-09-13 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPreparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_padrao_he', models.BooleanField(default=True, verbose_name='Método Padrão H&E')),
                ('notas_adicionais', models.TextField(blank=True, null=True, verbose_name='Notas Adicionais')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metodo_preparo', to='laudos.caso')),
            ],
        ),
    ]
