# Generated by Django 5.2.6 on 2025-09-21 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_etapa_statuses(apps, schema_editor):
    Caso = apps.get_model('laudos', 'Caso')

    for caso in Caso.objects.all():
        if caso.status == 'FINALIZADO':
            caso.macro_status = 'APROVADO'
            caso.preparo_status = 'APROVADO'
            caso.micro_status = 'APROVADO'
        else:
            caso.status = 'EM_MACROSCOPIA'
            caso.macro_status = 'EM_PROGRESSO'
            caso.preparo_status = 'PENDENTE'
            caso.micro_status = 'PENDENTE'
        caso.save(update_fields=['status', 'macro_status', 'preparo_status', 'micro_status'])


def normalize_log_actions(apps, schema_editor):
    LogAtividade = apps.get_model('laudos', 'LogAtividade')
    valid_actions = {
        'CASO_CRIADO',
        'MACRO_SALVO',
        'MACRO_SUBMETIDO',
        'MACRO_APROVADO',
        'PREPARO_SALVO',
        'PREPARO_SUBMETIDO',
        'PREPARO_APROVADO',
        'MICRO_SALVO',
        'MICRO_SUBMETIDO',
        'MICRO_APROVADO',
        'LAUDO_FINAL_APROVADO',
        'OUTRA',
    }

    for log in LogAtividade.objects.all():
        if log.acao not in valid_actions:
            log.acao = 'OUTRA'
            log.save(update_fields=['acao'])


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0003_macrodimensions_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='macro_aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='macro_aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macros_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='macro_preenchido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='macro_preenchido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macros_preenchidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='macro_status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROGRESSO', 'Em progresso'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovacao'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=30),
        ),
        migrations.AddField(
            model_name='caso',
            name='micro_aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='micro_aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micros_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='micro_preenchido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='micro_preenchido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micros_preenchidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='micro_status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROGRESSO', 'Em progresso'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovacao'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=30),
        ),
        migrations.AddField(
            model_name='caso',
            name='preparo_aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='preparo_aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparos_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='preparo_preenchido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='preparo_preenchido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparos_preenchidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='preparo_status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROGRESSO', 'Em progresso'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovacao'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='caso',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido'), ('EM_MACROSCOPIA', 'Em Macroscopia'), ('PENDENTE_MACRO_APROVACAO', 'Pendente de Aprovacao Macroscopica'), ('EM_PREPARO', 'Em Preparo/Coloracao'), ('PENDENTE_PREPARO_APROVACAO', 'Pendente de Aprovacao do Preparo'), ('EM_MICROSCOPIA', 'Em Microscopia'), ('PENDENTE_MICRO_APROVACAO', 'Pendente de Aprovacao Microscopica'), ('AGUARDANDO_APROVACAO_FINAL', 'Aguardando Aprovacao Final'), ('FINALIZADO', 'Finalizado')], default='RECEBIDO', max_length=40),
        ),
        migrations.AlterField(
            model_name='logatividade',
            name='acao',
            field=models.CharField(choices=[('CASO_CRIADO', 'Caso criado'), ('MACRO_SALVO', 'Macroscopia salva'), ('MACRO_SUBMETIDO', 'Macroscopia submetida'), ('MACRO_APROVADO', 'Macroscopia aprovada'), ('PREPARO_SALVO', 'Preparo salvo'), ('PREPARO_SUBMETIDO', 'Preparo submetido'), ('PREPARO_APROVADO', 'Preparo aprovado'), ('MICRO_SALVO', 'Microscopia salva'), ('MICRO_SUBMETIDO', 'Microscopia submetida'), ('MICRO_APROVADO', 'Microscopia aprovada'), ('LAUDO_FINAL_APROVADO', 'Laudo final aprovado'), ('OUTRA', 'Outra acao')], default='OUTRA', max_length=50),
        ),
        migrations.AlterField(
            model_name='logatividade',
            name='detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(seed_etapa_statuses, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(normalize_log_actions, reverse_code=migrations.RunPython.noop),
    ]
